name: Topic Handler

on:
  issue_comment:
    types: [created]

jobs:
  handle-topic:
    if: contains(github.event.comment.body, 'rawtopic')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Extract topic and run script
      run: |
        comment_body="${{ github.event.comment.body }}"
        # 使用正则表达式提取 'rawtopic' 后的内容
        topic=$(echo $comment_body | grep -oP 'rawtopic \K\S+')
        python check.py "$topic"
